import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthForm from "@/components/AuthForm";
import AuthenticationCtxProvider from "@/context/AuthContext";
import { Play } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

const play = Play({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-play",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${play.variable} relative `}>
        <AuthenticationCtxProvider>
          <Navbar />
        </AuthenticationCtxProvider>
        {children}
      </body>
    </html>
  );
}
