import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navigation/Navbar";
import AuthenticationCtxProvider from "../context/AuthContext";
import AddRestCtxProvider from "../context/addRestContext";
import {
  Play,
  Abril_Fatface,
  Bree_Serif,
  Exo_2,
  Acme,
  Didact_Gothic,
} from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

const bree = Bree_Serif({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bree",
});
const raleway = Didact_Gothic({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-rale",
});
const lemon = Acme({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lemon",
});
const abril = Abril_Fatface({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-abril",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${abril.variable} ${lemon.variable} ${raleway.variable} ${bree.variable} `}
    >
      <body className={inter.className}>
        <AuthenticationCtxProvider>
          <AddRestCtxProvider>
            <Navbar />
            {children}
          </AddRestCtxProvider>
        </AuthenticationCtxProvider>
      </body>
    </html>
  );
}
